#!/usr/bin/env python3
"""
Motor Offset Calibration Tool for AmazingHand

This tool helps you calibrate motor offsets by:
1. Reading current motor positions with the hand in neutral pose
2. Computing the offsets needed to zero out the IK angles
3. Saving to a TOML file

Usage:
1. Manually position the robot hand in its neutral/open pose
2. Run this script: python calibrate_motor_offsets.py
3. The script will read current positions and compute offsets
4. Offsets are saved to config/motor_offsets.toml
"""

import argparse
import logging
from pathlib import Path
import numpy as np

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def calibrate_offsets(port: str = "/dev/ttyUSB0", output_path: str = None):
    """Calibrate motor offsets by reading current positions in neutral pose"""
    from lerobot.motors.feetech import FeetechMotorsBus
    from lerobot.motors import Motor, MotorNormMode
    
    logger.info("=" * 60)
    logger.info("AmazingHand Motor Offset Calibration Tool")
    logger.info("=" * 60)
    
    # Create motor bus
    logger.info(f"Connecting to motors on {port}...")
    bus = FeetechMotorsBus(
        port=port,
        motors={
            "index_m1": Motor(15, "scs0009", MotorNormMode.RANGE_0_100),
            "index_m2": Motor(16, "scs0009", MotorNormMode.RANGE_0_100),
            "middle_m1": Motor(13, "scs0009", MotorNormMode.RANGE_0_100),
            "middle_m2": Motor(14, "scs0009", MotorNormMode.RANGE_0_100),
            "ring_m1": Motor(11, "scs0009", MotorNormMode.RANGE_0_100),
            "ring_m2": Motor(12, "scs0009", MotorNormMode.RANGE_0_100),
            "thumb_m1": Motor(17, "scs0009", MotorNormMode.RANGE_0_100),
            "thumb_m2": Motor(18, "scs0009", MotorNormMode.RANGE_0_100),
        },
    )
    
    try:
        bus.connect()
        logger.info("✓ Connected to motors")
        
        # Instructions
        print("\n" + "=" * 60)
        print("INSTRUCTIONS:")
        print("1. Manually position the robot hand in NEUTRAL/OPEN pose")
        print("   - All fingers should be straight and open")
        print("   - This is the 'zero' position the IK solver expects")
        print("2. Press ENTER when ready to measure positions...")
        print("=" * 60)
        input()
        
        # Read current positions
        logger.info("Reading current motor positions...")
        positions = bus.sync_read("Present_Position")
        
        # Convert positions to radians (assuming 0-100 scale maps to 0-4095 raw)
        # For SCS0009: 0% = 0 rad, 50% = π rad, 100% = 2π rad
        # So: radians = (percent / 100) * 2π - π
        logger.info("\nCurrent positions (in neutral pose):")
        offsets = {}
        for motor_name, pos_percent in sorted(positions.items()):
            # Convert percent to radians
            angle_rad = (pos_percent / 100.0) * 2 * np.pi - np.pi
            
            # Offset is the NEGATIVE of the current angle
            # (we want to ADD this offset to zero out the angle)
            offset = -angle_rad
            offsets[motor_name] = offset
            
            logger.info(
                f"  {motor_name}: {pos_percent:.2f}% = {angle_rad:+.4f}rad "
                f"→ offset = {offset:+.4f}rad ({offset * 180/np.pi:+.2f}°)"
            )
        
        # Generate TOML content
        finger_map = {
            ("index_m1", "index_m2"): "l_finger1",
            ("middle_m1", "middle_m2"): "l_finger2",
            ("ring_m1", "ring_m2"): "l_finger3",
            ("thumb_m1", "thumb_m2"): "l_finger4",
        }
        
        toml_content = "# Motor offsets for AmazingHand (Left)\n"
        toml_content += "# Generated by calibrate_motor_offsets.py\n"
        toml_content += "# These offsets center the robot's neutral position\n\n"
        
        for (m1, m2), finger_name in finger_map.items():
            toml_content += f"[[motors]]\n"
            toml_content += f'finger_name = "{finger_name}"\n\n'
            toml_content += f"[motors.motor1]\n"
            toml_content += f"offset = {offsets[m1]:.4f}\n"
            toml_content += f"invert = false\n\n"
            toml_content += f"[motors.motor2]\n"
            toml_content += f"offset = {offsets[m2]:.4f}\n"
            toml_content += f"invert = false\n\n"
        
        # Save to file
        if output_path is None:
            output_path = Path(__file__).parent / "src" / "lerobot" / "robots" / "lerobot_robot_amazinghand" / "lerobot_robot_amazinghand" / "config" / "motor_offsets.toml"
        else:
            output_path = Path(output_path)
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, "w") as f:
            f.write(toml_content)
        
        logger.info(f"\n✓ Offsets saved to: {output_path}")
        logger.info("\nTo use these offsets:")
        logger.info(f"  export LEROBOT_MOTOR_OFFSETS_PATH={output_path.absolute()}")
        logger.info("  OR place the file in the default location shown above")
        
        print("\n" + "=" * 60)
        print("Calibration complete!")
        print("=" * 60)
        
    finally:
        bus.disconnect()
        logger.info("Disconnected from motors")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Calibrate AmazingHand motor offsets")
    parser.add_argument(
        "--port",
        type=str,
        default="/dev/ttyUSB0",
        help="Serial port for motors (default: /dev/ttyUSB0)"
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output path for TOML file (default: auto-detect)"
    )
    
    args = parser.parse_args()
    calibrate_offsets(port=args.port, output_path=args.output)
